USE PedidosP
GO

-- DESHABILITAR CONSTRAINTS DE CLIENTE, CABEZERAP Y DETALLEP
ALTER TABLE catalogo.Cliente NOCHECK CONSTRAINT ALL
ALTER TABLE movimiento.CabezeraP NOCHECK CONSTRAINT ALL
ALTER TABLE movimiento.DetalleP NOCHECK CONSTRAINT ALL

-- AUMENTAR EL TAMAÑO DEL CAMPO CODCLI DEL CLIENTE Y CABEZERAP
ALTER TABLE catalogo.Cliente
ALTER COLUMN codcli CHAR(6)

ALTER TABLE movimiento.CabeceraP
ALTER COLUMN codcli CHAR(6)
GO

-- ACTUALIZAR VALORES DEL CAMPO CODCLI DEL CLIENTE Y CABEZERAP
UPDATE catalogo.Cliente
SET codcli = SUBSTRING(codcli,1,1) + '000' + SUBSTRING(codcli,DATALENGTH(codcli)-1,2)

UPDATE movimiento.CabezeraP
SET codcli = SUBSTRING(codcli,1,1) + '000' + SUBSTRING(codcli,DATALENGTH(codcli)-1,2)
GO

-- MODIFICAR TAMAÑO DEL CAMPO CODPED DE CABEZERAP Y DETALLEP
ALTER TABLE movimiento.CabezeraP
ALTER COLUMN codped CHAR(10)

ALTER TABLE movimiento.DetalleP
ALTER COLUMN codped CHAR(10)
GO

-- ACTUALIZAR VALORES DEL CAMPO CODPED DE CABEZERAP Y DETALLEP
UPDATE movimiento.CabezeraP
SET codped = 'PE000000' + SUBSTRING(codped,DATALENGTH(codped)-1,2)

UPDATE movimiento.DetalleP
SET codped = 'PE000000' + SUBSTRING(codped,DATALENGTH(codped)-1,2)
GO

-- HABILITAR CONSTRAINTS DE CLIENTE, CABEZERAP Y DETALLEP
ALTER TABLE catalogo.Cliente CHECK CONSTRAINT ALL
ALTER TABLE movimiento.CabezeraP CHECK CONSTRAINT ALL
ALTER TABLE movimiento.DetalleP CHECK CONSTRAINT ALL